# Generated by Django 4.2.6 on 2023-12-21 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments_on_article', to='api.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='api.newsarticle'),
        ),
    ]
